/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infox.telas;

import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import br.com.infox.dal.ModuloConexao;
import java.awt.Desktop;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;


public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/background/imagem.png"));
        Image image = icon.getImage();
        desktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        btnCliente = new javax.swing.JToggleButton();
        btnSairIniciar = new javax.swing.JToggleButton();
        btnEstoque = new javax.swing.JToggleButton();
        btnCaixa = new javax.swing.JToggleButton();
        btnSite = new javax.swing.JToggleButton();
        btnUsuario = new javax.swing.JToggleButton();
        btnAjuda = new javax.swing.JToggleButton();
        lblData = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inovac Technology");
        setBackground(new java.awt.Color(0, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/LogoIcon.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        desktop.setBackground(new java.awt.Color(60, 63, 65));
        desktop.setPreferredSize(new java.awt.Dimension(640, 480));
        desktop.setRequestFocusEnabled(false);
        getContentPane().add(desktop);
        desktop.setBounds(0, 0, 641, 480);

        btnCliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setText("Cadastro Cliente");
        btnCliente.setToolTipText("Cadastro de Clientes");
        btnCliente.setContentAreaFilled(false);
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCliente.setFocusable(false);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCliente);
        btnCliente.setBounds(710, 70, 138, 34);

        btnSairIniciar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnSairIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnSairIniciar.setText("Sair");
        btnSairIniciar.setToolTipText("Sair/Fechar");
        btnSairIniciar.setContentAreaFilled(false);
        btnSairIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSairIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairIniciar);
        btnSairIniciar.setBounds(710, 336, 138, 34);

        btnEstoque.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnEstoque.setForeground(new java.awt.Color(255, 255, 255));
        btnEstoque.setText("Cadastro Produtos");
        btnEstoque.setToolTipText("Cadastro de Produtos");
        btnEstoque.setContentAreaFilled(false);
        btnEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstoque);
        btnEstoque.setBounds(710, 116, 138, 34);

        btnCaixa.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnCaixa.setForeground(new java.awt.Color(255, 255, 255));
        btnCaixa.setText("Vendas");
        btnCaixa.setToolTipText("Vendas");
        btnCaixa.setBorder(null);
        btnCaixa.setContentAreaFilled(false);
        btnCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCaixa);
        btnCaixa.setBounds(710, 160, 138, 34);

        btnSite.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnSite.setForeground(new java.awt.Color(255, 255, 255));
        btnSite.setText("Landing Page");
        btnSite.setToolTipText("SIte da Inovac");
        btnSite.setContentAreaFilled(false);
        btnSite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSite);
        btnSite.setBounds(710, 204, 138, 34);

        btnUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setText("Cadastro de Usuário");
        btnUsuario.setToolTipText("Cadastro de Usuários");
        btnUsuario.setContentAreaFilled(false);
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuario);
        btnUsuario.setBounds(710, 247, 138, 34);

        btnAjuda.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnAjuda.setForeground(new java.awt.Color(255, 255, 255));
        btnAjuda.setText("Sobre");
        btnAjuda.setToolTipText("Sobre");
        btnAjuda.setContentAreaFilled(false);
        btnAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjuda);
        btnAjuda.setBounds(710, 293, 138, 34);

        lblData.setBackground(new java.awt.Color(204, 204, 204));
        lblData.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblData.setForeground(new java.awt.Color(204, 204, 204));
        lblData.setText("Data");
        getContentPane().add(lblData);
        lblData.setBounds(670, 440, 220, 28);

        lblUsuario.setBackground(new java.awt.Color(204, 204, 204));
        lblUsuario.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblUsuario.setText("Usuário");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(670, 410, 220, 28);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/background/TelaMenu (1).png"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 910, 490);
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 5, 5);

        setSize(new java.awt.Dimension(911, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // ao ativar a janela, mude e atualize a data:
        Date data = new Date();
        // atenção ao .toString
        //lblData.setText(data.toString());
        // formatando a data
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        desktop.add(cliente);

    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnSairIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairIniciarActionPerformed
        // Fecha o Programa
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja Sair do Programa?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_btnSairIniciarActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        // Abre a tela de estoque
        TelaEstoque estoque = new TelaEstoque();
        estoque.setVisible(true);
        desktop.add(estoque);
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
    
        TelaCaixa caixa = new TelaCaixa();
        caixa.setVisible(true);
        desktop.add(caixa);
        caixa.setar_campos();
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiteActionPerformed
        // TODO add your handling code here:
        Desktop desk = java.awt.Desktop.getDesktop(); try { desk.browse(new java.net.URI("https://inovac.netlify.app/")); } catch (Exception e) { e.printStackTrace(); }
    }//GEN-LAST:event_btnSiteActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // as linhas abaixo abrir o form TelaUsuario dentro do desktop pane
       
        TelaUsuario usuario = new TelaUsuario();
        
        usuario.setVisible(true);
        desktop.add(usuario);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        // Abre tela 'sobre'
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_btnAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAjuda;
    private javax.swing.JToggleButton btnCaixa;
    private javax.swing.JToggleButton btnCliente;
    private javax.swing.JToggleButton btnEstoque;
    private javax.swing.JToggleButton btnSairIniciar;
    private javax.swing.JToggleButton btnSite;
    private javax.swing.JToggleButton btnUsuario;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
